Repository openshift/aws-efs-csi-driver-operator, pull requests merged in 2021-08, with the labels that each got.

#13 Bug 1990137: Make minor fixes for automatic creation of EFS volumes
  README.md
  assets/assets.go
  pkg/efscreate/create.go
  pkg/efscreate/efs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#14 Bug 1990146: some controllers missing livenessProbe
  assets/controller.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#15 Bug 1993851: Add Red Hat logo
  config/manifests/4.9/aws-efs-csi-driver-operator.clusterserviceversion.yaml
Labels: bugzilla/severity-medium, approved, bugzilla/valid-bug, lgtm

#16 Bug 1994973: Fix olm.skipRange and currentCSV
  config/manifests/4.9/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/manifests/aws-efs-csi-driver-operator.package.yaml
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm
