Repository openshift/aws-efs-csi-driver-operator, pull requests merged in 2021-12, with the labels that each got.

#25 Add arm64 arch label to CSV
  config/manifests/4.10/aws-efs-csi-driver-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#24 Bug 2026668: Add "disconnected" annotation.
  config/manifests/4.10/aws-efs-csi-driver-operator.clusterserviceversion.yaml
Labels: bugzilla/severity-medium, approved, bugzilla/valid-bug, lgtm

#26 Revert "Add "disconnected" and CSI annotations."
  config/manifests/4.10/aws-efs-csi-driver-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#27 Bug 2028484: CSI driver's livenessprobe does not respect operator's loglevel
  assets/controller.yaml
  assets/node.yaml
Labels: approved, lgtm

#28 Increase provisioning/deletion timeout
  assets/controller.yaml
Labels: approved, lgtm

#29 Bug 2029521: Eliminate parallelism in external-provisioner
  assets/controller.yaml
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm
