Repository openshift/aws-efs-csi-driver-operator, pull requests merged in 2021-07, with the labels that each got.

#4 Add OLM manifests
  assets/node.yaml
  manifests/4.9/aws-efs-csi-driver-operator.v4.9.0.clusterserviceversion.yaml
  manifests/4.9/image-references
  manifests/art.yaml
  manifests/aws-efs-csi-driver-operator.package.yaml
Labels: approved, lgtm

#6 Add hack/create-bundle
  README.md
  hack/.gitignore
  hack/create-bundle
Labels: approved, lgtm

#7 [ART-3172] Fix manifests for ART builds
  manifests/4.9/image-references
Labels: approved, lgtm

#8 Add dynamic provisioning
  assets/controller.yaml
  assets/controller_sa.yaml
  assets/credentials.yaml
  assets/node.yaml
  assets/rbac/controller_privileged_binding.yaml
  assets/rbac/kube_rbac_proxy_binding.yaml
  assets/rbac/kube_rbac_proxy_role.yaml
  assets/rbac/prometheus_role.yaml
  assets/rbac/prometheus_rolebinding.yaml
  assets/rbac/provisioner_binding.yaml
  assets/rbac/provisioner_role.yaml
  assets/service.yaml
  assets/servicemonitor.yaml
  manifests/4.9/aws-efs-csi-driver-operator.v4.9.0.clusterserviceversion.yaml
  manifests/4.9/image-references
  pkg/operator/starter.go
  pkg/operator/staticresource/operator.go
Labels: approved, lgtm

#9 Bug 1986501: Fix bundle for making it easier to consume from CI
  config/bundle.Dockerfile
  config/manifests/4.9/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/manifests/4.9/image-references
  config/manifests/art.yaml
  config/manifests/aws-efs-csi-driver-operator.package.yaml
  config/metadata/annotations.yaml
  hack/create-bundle
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#10 Bug 1986419: Fix image-references
  config/manifests/4.9/image-references
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#11 Bug 1986419: art.yaml: refer to correct filename
  config/manifests/art.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
