Repository openshift/aws-efs-csi-driver-operator, pull requests merged in 2022-06, with the labels that each got.

#47 Bug 2090268: Allow the operator to run on a worker node
  config/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
Labels: bugzilla/severity-high, approved, bugzilla/valid-bug, lgtm

#48 Bug 2094525: Fix lower bound of skip range to allow operator upgrades
  config/manifests/art.yaml
  config/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
Labels: bugzilla/severity-medium, approved, bugzilla/valid-bug, lgtm

#49 Bug 2094548: Fix lower bound to allow upgrades
  config/manifests/4.10/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  config/manifests/art.yaml
Labels: cherry-pick-approved, bugzilla/severity-medium, approved, bugzilla/valid-bug, lgtm, backport-risk-assessed

#46 Find suitable container tool
  hack/create-bundle
Labels: approved, lgtm
