Repository openshift/aws-efs-csi-driver-operator, pull requests merged in 2023-07, with the labels that each got.

#77 STOR-1376: Add STS support
  assets/credentials.yaml
  config/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/operator/starter.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/credentialsrequestcontroller/credentials_request_controller.go
  vendor/github.com/openshift/library-go/pkg/operator/csi/csicontrollerset/csi_controller_set.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#75 STOR-1065: Rework sidecar bindings to bind common ClusterRoles
  assets/rbac/lease_leader_election_role.yaml
  assets/rbac/lease_leader_election_rolebinding.yaml
  assets/rbac/main_provisioner_binding.yaml
  assets/rbac/provisioner_role.yaml
  pkg/operator/starter.go
  pkg/operator/staticresource/operator.go
Labels: px-approved, docs-approved, qe-approved, approved, lgtm, jira/valid-reference

#79 OCPBUGS-16783: Chore: Update OWNERS
  OWNERS
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference
