Repository openshift/aws-efs-csi-driver-operator, pull requests merged in 2023-08, with the labels that each got.

#80 OCPBUGS-16493: Bump library-go to remove dependency on goproxy
  go.mod
  go.sum
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/apimachinery/pkg/types/namespacedname.go
  vendor/k8s.io/apimachinery/pkg/util/wait/loop.go
  vendor/k8s.io/apiserver/pkg/cel/common/values.go
  vendor/k8s.io/apiserver/pkg/server/options/etcd.go
  vendor/k8s.io/apiserver/pkg/server/storage/storage_factory.go
  vendor/k8s.io/apiserver/pkg/storage/etcd3/healthcheck.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go
  vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/k8s.io/kube-openapi/pkg/handler/handler.go
  vendor/modules.txt
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
  vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/metrics/metrics.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/types.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/apis/migration/v1alpha1/zz_generated.deepcopy.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/clientset.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/scheme/register.go
  vendor/sigs.k8s.io/kube-storage-version-migrator/pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#83 OCPBUGS-17244: Add better description
  config/manifests/art.yaml
  config/manifests/stable/aws-efs-csi-driver-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#84 OCPBUGS-17244: Fix links to documentation
  config/manifests/art.yaml
Labels: qe-approved, approved, lgtm, jira/valid-bug, jira/valid-reference

#82 [release-4.13] OCPBUGS-16250: Add management workloads annotations
  assets/controller.yaml
  assets/node.yaml
Labels: cherry-pick-approved, approved, lgtm, backport-risk-assessed, jira/severity-moderate, jira/valid-bug, jira/valid-reference
